# Generated by Django 4.2.30 on 2026-10-04 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Academic', 'Academic'), ('Conference', 'Conference'), ('Gala', 'Gala'), ('Career', 'Career'), ('Student Life', 'Student Life'), ('Workshop', 'Workshop'), ('Athletics', 'Athletics'), ('Other', 'Other')], default='Academic', max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], db_index=True, default='Draft', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['status', 'date'], name='events_even_status_d859e9_idx')],
            },
        ),
    ]
