# Generated by Django 4.2.30 on 2026-10-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('category', models.CharField(choices=[('Venue & Facility', 'Venue & Facility'), ('Catering & Hospitality', 'Catering & Hospitality'), ('Audio/Visual & Rigging', 'Audio/Visual & Rigging'), ('Marketing & Signage', 'Marketing & Signage'), ('Security & Staffing', 'Security & Staffing'), ('Logistics & Transport', 'Logistics & Transport'), ('Other', 'Other')], default='Other', max_length=100)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(db_index=True)),
                ('payment_status', models.CharField(choices=[('Approved', 'Approved'), ('Paid', 'Paid'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.event')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-date', '-created_date'],
            },
        ),
    ]
