# Generated by Django 4.2.30 on 2026-10-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_authorized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_ref',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Catering & Hospitality', 'Catering & Hospitality'), ('Venue & Facility', 'Venue & Facility'), ('Audio/Visual & Rigging', 'Audio/Visual & Rigging'), ('Marketing & Signage', 'Marketing & Signage'), ('Security & Staffing', 'Security & Staffing'), ('Logistics & Transport', 'Logistics & Transport'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending Approval', 'Pending Approval'), ('Pending', 'Pending'), ('Invoiced', 'Invoiced'), ('Reconciled', 'Reconciled'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
