# Generated by Django 4.2.30 on 2026-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('Catering', 'Catering'), ('Audio/Visual', 'Audio/Visual'), ('Staging & Lighting', 'Staging & Lighting'), ('Security', 'Security'), ('Photography', 'Photography'), ('Janitorial', 'Janitorial'), ('Decor & Furniture', 'Decor & Furniture'), ('Other', 'Other')], default='Other', max_length=100)),
                ('contact_person', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Pending', 'Pending')], default='Active', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
