# Generated by Django 4.2.30 on 2026-10-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='active_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vendors', to='events.event'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='coi_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sla_status',
            field=models.CharField(choices=[('Cleared', 'Cleared (Insured & Active)'), ('Expiring Soon', 'Expiring Soon (< 30d)'), ('Pending Renewal', 'Pending Renewal')], default='Cleared', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tier',
            field=models.CharField(default='Tier 1', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='service_type',
            field=models.CharField(choices=[('Catering', 'Catering & Hospitality'), ('Audio/Visual', 'AV & Production'), ('Staging & Lighting', 'Stage & Rigging'), ('Security', 'Security & Logistics'), ('Photography', 'Photography & Media'), ('Janitorial', 'Facilities & Sanitation'), ('Decor & Furniture', 'Decor & Furniture'), ('Logistics & Transport', 'Logistics & Transport'), ('Other', 'Other')], default='Other', max_length=100),
        ),
        migrations.CreateModel(
            name='VendorDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dock_bay', models.CharField(default='Bay 3 Freight', max_length=100)),
                ('call_time', models.CharField(default='07:00 AM EDT', max_length=50)),
                ('crew_passes', models.PositiveIntegerField(default=10)),
                ('vehicles', models.PositiveIntegerField(default=2)),
                ('po_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('Cleared Dock', 'Cleared Dock'), ('In Transit', 'In Transit'), ('Awaiting Escort', 'Awaiting Escort'), ('Dispatched', 'Dispatched')], default='Cleared Dock', max_length=50)),
                ('pass_number', models.CharField(default='DK-9812', max_length=50)),
                ('lead_name', models.CharField(blank=True, default='', max_length=255)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_dispatches', to='events.event')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='vendors.vendor')),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
