# Generated by Django 4.2.30 on 2026-10-05 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='department',
            field=models.CharField(blank=True, default='Academic Operations', max_length=100),
        ),
        migrations.AddField(
            model_name='budget',
            name='fiscal_year',
            field=models.CharField(default='FY 2026', max_length=20),
        ),
    ]
