# Generated by Django 4.2.30 on 2026-10-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('conflict', 'Resource Conflict'), ('registration', 'New Registration'), ('event', 'Event Approaching'), ('vendor', 'Vendor Assigned'), ('budget', 'Budget Threshold Warning'), ('maintenance', 'Resource Maintenance'), ('general', 'General Alert')], default='general', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link_url', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
