# Generated by Django 4.2.30 on 2026-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('success', 'Success')], default='info', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='source_code',
            field=models.CharField(blank=True, default='SYSTEM', max_length=50),
        ),
    ]
