# Generated by Django 4.2.30 on 2026-10-04 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('Auditorium', 'Auditorium'), ('Classroom', 'Classroom'), ('Projector', 'Projector'), ('Microphone', 'Microphone'), ('Sound System', 'Sound System'), ('LED Screen', 'LED Screen'), ('Camera', 'Camera'), ('Generator', 'Generator'), ('Tables', 'Tables'), ('Chairs', 'Chairs'), ('Other', 'Other')], default='Other', max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Assigned', 'Assigned'), ('Maintenance', 'Maintenance')], db_index=True, default='Available', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_date', models.DateField(db_index=True)),
                ('time_a', models.CharField(max_length=100)),
                ('time_b', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('event_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_a', to='events.event')),
                ('event_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts_as_b', to='events.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='resources.resource')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Pending', 'Pending'), ('Released', 'Released'), ('Conflicted', 'Conflicted')], default='Confirmed', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_allocations', to='events.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='resources.resource')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
